### ISSUE TITLE
Dropbox Login Error

### ISSUE THREAD

**Issue by blabdude** [ginatrapani/todo.txt-android#461]
I have tried logging into Dropbox on Todo.txt but it fails every time.
The following toast pops up:

Network error:
com.dropbox.client.DropboxException:
HTTP/1.1 400 Bad Request

I have tried this on multiple devices, with multiple accounts and builds 1-21 but all with the same result.

**Comment by ginatrapani** [comment]
Fixed in the current build, release 56
