### ISSUE TITLE
Marking an item as done removes priority label

### ISSUE THREAD

**Issue by bartgenuit** [ginatrapani/todo.txt-android#464]
Using v2.2 of the app, marking an item as done removes the priority label. However, it would be nice to keep this label for future reference.

**Comment by schilke** [comment]
If I'm not mistaken this is the standard behaviour. 
See the documentation: [Rule 1: A completed task starts with an x](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-1-a-completed-task-starts-with-an-x)

**Comment by bartgenuit** [comment]
Well, in QTodoTxt for example, they put completed tasks as:

> x (A) Find ticket prices

which imho is fine with regards to alphabetical sorting. In the documentation you linked to it states

> Many Todo.txt clients discard priority on task completion. To preserve it, use the key:value format described below (for example, pri:A).

However, setting the priority in this manner makes it incompatible with the app.

**Comment by ginatrapani** [comment]
Hi - yes, this Todo.txt client discards priority on completion by design. Sorry about that!
